// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

////
Base the file name and the ID on the module title. For example:
* file name: ref-my-reference-a.adoc
* ID: [id="ref-my-reference-a_{context}"]
* Title: = My reference A

The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken.

The `context` attribute enables module reuse. Every module ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
////

[id="ref_creating-multiproduct_{context}"]
= Creating Multiproduct

A well-organized reference module enables users to scan it quickly to find the details they want.
AsciiDoc markup to consider for reference data:

.Labeled list
Term 1:: Definition
Term 2:: Definition

.Table
[options="header"]
|====
|Column 1|Column 2|Column 3
|Row 1, column 1|Row 1, column 2|Row 1, column 3
|Row 2, column 1|Row 2, column 2|Row 2, column 3
|====

