// This assembly is included in the following assemblies:
//
// <List assemblies here, each on a new line>

////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context-of-assembly_deploying-your-multiproduct-locally: {context}]

////
Base the file name and the ID on the assembly title. For example:
* file name: assembly-my-user-story.adoc
* ID: [id="assembly-my-user-story_{context}"]
* Title: = My user story

The ID is an anchor that links to the module. Avoid changing it after the module has been published to ensure existing links are not broken. Include {context} in the ID so the assembly can be reused.
////

ifndef::context[]
[id="assembly_deploying-your-multiproduct-locally"]
endif::[]
ifdef::context[]
[id="assembly_deploying-your-multiproduct-locally_{context}"]
endif::[]
= Deploying your Multiproduct Locally
////
If the assembly covers a task, start the title with a verb in the gerund form, such as Creating or Configuring.
////

:context: assembly_deploying-your-multiproduct-locally

////
The `context` attribute enables module reuse. Every module ID includes {context}, which ensures that the module has a unique ID so you can include it multiple times in the same guide.
////
LinkedIn Deployment (LID) is the toolset that enables deployment for Desktop development, PCx, and production deployments across all our fabrics. It includes the definition and the implementation of fabrics and fabric groups.
The lifecycle for Deployment and Topology starts at Product creation time.
The Topology information that is defined for your desktop deployments will be used to provide the basis for production deployments. 
[role="_abstract"]
This paragraph is the assembly introduction. It explains what the user will accomplish by working through the modules in the assembly and sets the context for the user story the assembly is based on. The text that immediately follows the `[role="_abstract"]` tag is used for search metadata.

== Prerequisites


* Ensure that you have LinkedIn Engineering Tools installed.

////
The following include statements pull in the module files that comprise the assembly. Include any combination of concept, procedure, or reference modules required to cover the user story. You can also include other assemblies.

include::modules/TEMPLATE_CONCEPT_explaining_a_concept.adoc[leveloffset=+1]
////

include::modules/local-deployment/con_understanding-multiproduct-structure.adoc[leveloffset=+1]

include::modules/local-deployment/proc_deploying-locally.adoc[leveloffset=+1]

include::modules/local-deployment/ref_creating-multiproduct.adoc[leveloffset=+1]

////
[leveloffset=+1] ensures that when a module title is a level 1 heading (= Title), the heading will be interpreted as a level-2 heading (== Title) in the assembly. Use [leveloffset=+2] and [leveloffset=+3] to nest modules in an assembly.

include::modules/TEMPLATE_PROCEDURE_doing_one_procedure.adoc[leveloffset=+2]

include::modules/TEMPLATE_PROCEDURE_reference-material.adoc[leveloffset=2]
////

[role="_additional-resources"]
== Additional resources
(or Next steps)

////
Optional. Delete if not used.
////

* For more details on LID, see the link:https://iwww.corp.linkedin.com/wiki/cf/pages/viewpage.action?pageId=48094297[LinkedIn Deployment].

////
Restore the context to what it was before this assembly.
////
ifdef::parent-context-of-assembly_deploying-your-multiproduct-locally[:context: {parent-context-of-assembly_deploying-your-multiproduct-locally}]
ifndef::parent-context-of-assembly_deploying-your-multiproduct-locally[:!context:]

